### PR TITLE
Relax constraint on `impl Future for SpawnWithHandle`

### LINKED ISSUE #903: impl Future for SpawnWithHandle is too strict to be useful
Hey, on `0.2.0-beta`, you can only use `spawn_with_handle` with Futures returning unit, which isn't very useful for a handle. I think this can be relaxed, but I am not sure.

```rust
impl<F> Future for SpawnWithHandle<F>
    where F: Future<Item = (), Error = Never> + Send + 'static,
          F::Item: Send,
          F::Error: Send,
{
```

Can we make it accept any `Item` and `Error`, as long as they both implement `Send`?

### PR DESCRIPTION
**Pull request by Nemo157**
The constraint that you must have `Future<Item = (), Error = Never>`
appears to have been a mistake, the rest of the code already intends to
support passing any `Send`able `Item` or `Error` back.

Also add doc tests showing passing both items and errors back to ensure
test coverage.

Fixes #903

### CODE REVIEW

File: futures-executor/src/spawn.rs [hunk 1]
```diff
@@ -51,14 +51,58 @@ pub struct SpawnWithHandle<F>(Option<F>);
...
+///
+/// # Examples
+///
+/// ```
+/// # extern crate futures;
+/// # extern crate futures_executor;
+/// #
+/// use futures::prelude::*;
+/// use futures::future;
+/// use futures_executor::{block_on, spawn_with_handle};
```
Comment (Nemo157) [inline futures-executor/src/spawn.rs]: One question, should this be accessed via `futures::executor` instead of `futures_executor`? What is the policy on using the facade paths vs local paths in examples?

Comment (cramertj) [reply futures-executor/src/spawn.rs]: I'd use the facade path to e consistent with the other examples.

**Comment by cramertj** [comment]
thanks!
