### PR TITLE
Fix the stack overflow in the compat layers (#1283)

### LINKED ISSUE #1283: Stack overflow in compat layers
Minimal repro for `futures` `0.3.0-alpha.7` provided by @andreasots (https://gist.github.com/andreasots/4ea3982036ad703158ee3ddc11376eee):

```rust
#![feature(await_macro, async_await, futures_api)]

use tokio::timer::Delay;
use std::time::Instant;
use futures::prelude::*;
use futures::compat::Future01CompatExt;

fn main() {
    let f = async {
        await!(Delay::new(Instant::now()).compat());
    };
    tokio::run(f.unit_error().boxed().compat());
}
```

Slightly snipped stack trace (can probably have more unnecessary lines removed):

```text
#42 0x000055555556d669 in <futures_util::compat::compat03to01::CurrentRef as core::task::wake::UnsafeWake>::clone_raw (self=0x1)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat03to01.rs:98
#43 0x000055555556d87a in <core::task::wake::Waker as core::clone::Clone>::clone (self=0x7ffff63fce48) at libcore/task/wake.rs:72
#44 0x000055555556d563 in futures_util::compat::compat01to03::<impl core::convert::From<futures_util::compat::compat01to03::WakerToHandle<'a>> for futures::task_impl::NotifyHandle>::from (handle=...)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat01to03.rs:61
#45 0x000055555556cc23 in <T as core::convert::Into<U>>::into (self=...) at libcore/convert.rs:456
#46 0x00005555555682c8 in futures::task_impl::with_notify::{{closure}}::{{closure}} () at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:497
#47 0x00005555556544db in futures::task_impl::core::BorrowedUnpark::to_owned (self=0x7ffff62012a8) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/core.rs:49
#48 0x000055555564f231 in futures::task_impl::std::BorrowedUnpark::to_owned (self=0x7ffff63fc988) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/std/mod.rs:124
[...]
#20649 0x0000555555652f2f in futures::task_impl::current::{{closure}} (borrowed=0x7ffff63fc980) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:116
#20650 0x0000555555652eaa in futures::task_impl::with (f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:45
#20651 0x0000555555652ef1 in futures::task_impl::current () at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:115
#20652 0x000055555556d669 in <futures_util::compat::compat03to01::CurrentRef as core::task::wake::UnsafeWake>::clone_raw (self=0x1)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat03to01.rs:98
#20653 0x000055555556d87a in <core::task::wake::Waker as core::clone::Clone>::clone (self=0x7ffff63fce48) at libcore/task/wake.rs:72
#20654 0x000055555556d563 in futures_util::compat::compat01to03::<impl core::convert::From<futures_util::compat::compat01to03::WakerToHandle<'a>> for futures::task_impl::NotifyHandle>::from (handle=...)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat01to03.rs:61
#20655 0x000055555556cc23 in <T as core::convert::Into<U>>::into (self=...) at libcore/convert.rs:456
#20656 0x00005555555682c8 in futures::task_impl::with_notify::{{closure}}::{{closure}} () at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:497
#20657 0x00005555556544db in futures::task_impl::core::BorrowedUnpark::to_owned (self=0x7ffff63fc5d8) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/core.rs:49
#20658 0x000055555564f231 in futures::task_impl::std::BorrowedUnpark::to_owned (self=0x7ffff63fc988) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/std/mod.rs:124
#20659 0x0000555555652f2f in futures::task_impl::current::{{closure}} (borrowed=0x7ffff63fc980) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:116
[...]
#20666 0x0000555555569cfb in futures_util::compat::compat01to03::<impl core::future::future::Future for futures_util::compat::compat::Compat<Fut>>::poll::{{closure}} ()
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat01to03.rs:26
#20667 0x000055555556b6cc in futures::task_impl::std::set (task=0x7ffff63fc980, f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/std/mod.rs:78
#20668 0x0000555555568247 in futures::task_impl::with_notify::{{closure}} (task=0x7ffff63fcfe0) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:505
#20669 0x00005555555683b8 in futures::task_impl::with (f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:45
#20670 0x000055555556817b in futures::task_impl::with_notify (notify=0x7ffff63fcad8, id=0, f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:496
#20671 0x000055555556aa8e in futures_util::compat::compat01to03::<impl core::future::future::Future for futures_util::compat::compat::Compat<Fut>>::poll (self=..., lw=0x7ffff63fce48)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat01to03.rs:25
[...]
#20682 0x0000555555569ab1 in futures_util::compat::compat03to01::<impl futures::future::Future for futures_util::compat::compat::Compat<Fut>>::poll::{{closure}} (inner=..., lw=0x7ffff63fce48)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat03to01.rs:21
#20683 0x0000555555569c4c in futures_util::compat::compat03to01::with_context (compat=0x7ffff6a21088, f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat03to01.rs:122
#20684 0x000055555556aab3 in futures_util::compat::compat03to01::<impl futures::future::Future for futures_util::compat::compat::Compat<Fut>>::poll (self=0x7ffff6a21088)
    at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.7/src/compat/compat03to01.rs:21
#20685 0x0000555555651205 in <alloc::boxed::Box<F> as futures::future::Future>::poll (self=0x7ffff6a540c8) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/future/mod.rs:113
#20686 0x00005555555eef13 in <futures::task_impl::Spawn<T>>::poll_future_notify::{{closure}} (f=0x7ffff6a540c8) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:314
#20687 0x00005555555ef1d0 in <futures::task_impl::Spawn<T>>::enter::{{closure}} () at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:388
#20688 0x00005555555da34c in futures::task_impl::std::set (task=0x7ffff63fcfe0, f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/std/mod.rs:78
#20689 0x00005555555ef04b in <futures::task_impl::Spawn<T>>::enter (self=0x7ffff6a540a0, unpark=..., f=...) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:388
#20690 0x00005555555eee7a in <futures::task_impl::Spawn<T>>::poll_future_notify (self=0x7ffff6a540a0, notify=0x7ffff63fd9e8, id=140737331413120) at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.24/src/task_impl/mod.rs:314
#20691 0x00005555555cd065 in tokio_threadpool::task::Task::run::{{closure}} () at /home/andreas/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.7/src/task/mod.rs:127
```

The issue appears to be because `CurrentRef` delays getting the task until it's needed it waits too long and the task's waker has already been replaced with a `NotifyWaker` that tries to use the `CurrentRef`, making a loop. Removing `CurrentRef` and producing a `CurrentOwned` straight away when needed fixes it. I assume `CurentRef` is there because `CurrentOwned` can be expensive with the `Arc` and accessing `task::current`, maybe there's an alternative optimization that could be done and will be safe against `task::current` being changed under it?

cc @seanmonstar since you introduced `CurrentRef`

### PR DESCRIPTION
**Pull request by andreasots**
Since the `LocalWaker` is dropped immediately after polling the `task01::Task` can be stored on the stack.

Fixes #1283.

### CODE REVIEW

**Comment by Arnavion** [comment]
Maybe also fix and uncomment the doctests in futures-util/src/compat/tokio.rs so that this doesn't happen again.

File: futures-util/src/compat/compat03as01.rs [hunk 1]
```diff
@@ -103,32 +103,53 @@ where
...
+        &self.inner
     }
 }
 
-struct CurrentRef;
+struct Current(task01::Task);
+
+impl Current {
+    fn new() -> Current {
+        Current(task01::current())
```
Comment (seanmonstar) [inline futures-util/src/compat/compat03as01.rs]: So this brings us back to cloning the `Task` on every single poll, even if the future doesn't need to clone it. Do we fully understand why the stack overflow is happening?

Comment (cramertj) [reply futures-util/src/compat/compat03as01.rs]: @Nemo157 said in #1283 
> The issue appears to be because CurrentRef delays getting the task until it's needed it waits too long and the task's waker has already been replaced with a NotifyWaker that tries to use the CurrentRef, making a loop. Removing CurrentRef and producing a CurrentOwned straight away when needed fixes it. I assume CurentRef is there because CurrentOwned can be expensive with the Arc and accessing task::current, maybe there's an alternative optimization that could be done and will be safe against task::current being changed under it?

Comment (cramertj) [reply futures-util/src/compat/compat03as01.rs]: @seanmonstar This is probably a single atomic op, right? In comparison, the `UnsafeWake::clone_raw` implementation requires actually allocating a new `Arc`-- that seems far more expensive to me, so I wouldn't think this to be that big of a deal. Do you disagree?

Comment (cramertj) [reply futures-util/src/compat/compat03as01.rs]: If not, I'd prefer to land this and issue a release to get things working again, then iterate towards a better (but still correct) solution.

Comment (seanmonstar) [reply futures-util/src/compat/compat03as01.rs]: I'm good with getting a fix first. It'd help if the fix includes a test that was failing, so new attempts at optimizing won't regress again.

Comment (cramertj) [reply futures-util/src/compat/compat03as01.rs]: This change includes a test [here](https://github.com/rust-lang-nursery/futures-rs/pull/1286/files#diff-0104b5b5ecf10b5da0c47b19c2f1745bR1) -- does that work for you?

Comment (Nemo157) [reply futures-util/src/compat/compat03as01.rs]: From the example and stacktrace in the linked issue the following happens:

 1. `tokio::run` calls into `<futures::task_impl::Spawn<T>>::enter` which sets up the `Task` in TLS
 2. `futures_util::compat::compat03to01::<impl futures::future::Future for futures_util::compat::compat::Compat<Fut>>::poll` creates a `CurrentRef`, then calls the wrapped future (the `async` block) with it as the `LocalWaker` in the context
 3. the `std` libraries async layers are passed through (probably shouldn’t have fully snipped those)
 4. `futures_util::compat::compat01to03::<impl core::future::future::Future for futures_util::compat::compat::Compat<Fut>>::poll` takes a reference to the current `LocalWaker` on the context and updates the `Notify` on the task to be this wrapped reference as `WakerToHandle`
 5. `<tokio_timer::delay::Delay as futures::future::Future>::poll` calls `futures::task_impl::current`, this attempts to acquire an owned handle to the current `Notify`
 6. to create the owned handle (`NotifyWaker`) `futures_util::compat::compat01to03::<impl core::convert::From<futures_util::compat::compat01to03::WakerToHandle<'a>> for futures::task_impl::NotifyHandle>::from` attempts to clone the `LocalWaker` it has
 7. to clone the waker (into a `CurrentOwned`) `<futures_util::compat::compat03to01::CurrentRef as core::task::wake::UnsafeWake>::clone_raw` calls `futures::task_impl::current` to get the current task
 8. `goto 6`

Comment (seanmonstar) [reply futures-util/src/compat/compat03as01.rs]: Yep, that's great!

**Comment by cramertj** [comment]
Thanks so much for the fix! I'll get a release out today.
